# Generated by Django 4.1 on 2023-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0003_remove_comment_author_comment_email_comment_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="author_images/"),
        ),
    ]
