# Generated by Django 4.1 on 2023-07-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image",
            field=models.ImageField(default="img/def.jpg", upload_to="img/"),
        ),
    ]
